{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ksbecho.serviceAccountName" . }}
  labels:
{{ include "ksbecho.labels" . | nindent 4 }}
{{- end -}}
