apiVersion: v1
kind: Service
metadata:
  name: {{ include "ksbecho.fullname" . }}
  labels:
    {{- include "ksbecho.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ksbecho.name" . }}
    helm.sh/chart: {{ include "ksbecho.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ksbecho.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
